

const KEY="talatShamaliAccountingV3";
const empty={daily:[],employees:[],payments:[],archive:[],abuFadi:[],expenses:[],purchases:[],expenseItems:[],purchaseItems:[],monthlyBills:[],attendance:[],advances:[],inventory:[],suppliers:[],cash:[]};
let db=loadDb();
let editingEmployeeId=null;
let deferredInstallPrompt=null;
const $=id=>document.getElementById(id);
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=n=>Number(n||0).toFixed(2)+" JD";
const monthOf=d=>String(d||"").slice(0,7);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadDb(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"null")||empty;return {daily:Array.isArray(raw.daily)?raw.daily:[],employees:Array.isArray(raw.employees)?raw.employees:[],payments:Array.isArray(raw.payments)?raw.payments:[],archive:Array.isArray(raw.archive)?raw.archive:[],abuFadi:Array.isArray(raw.abuFadi)?raw.abuFadi:[],expenses:Array.isArray(raw.expenses)?raw.expenses:[],purchases:Array.isArray(raw.purchases)?raw.purchases:[],expenseItems:Array.isArray(raw.expenseItems)?raw.expenseItems:[],purchaseItems:Array.isArray(raw.purchaseItems)?raw.purchaseItems:[],monthlyBills:Array.isArray(raw.monthlyBills)?raw.monthlyBills:[],attendance:Array.isArray(raw.attendance)?raw.attendance:[],advances:Array.isArray(raw.advances)?raw.advances:[],inventory:Array.isArray(raw.inventory)?raw.inventory:[],suppliers:Array.isArray(raw.suppliers)?raw.suppliers:[],cash:Array.isArray(raw.cash)?raw.cash:[]};}catch(e){return {...empty}}}
db.employees=db.employees.map(e=>({...e,id:e.id??Date.now()+Math.random(),name:String(e.name||''),job:String(e.job||''),salary:Number(e.salary||0),status:e.status||'active'}));
db.daily=db.daily.map(x=>({...x,expenses:Number(x.expenses||0),purchases:Number(x.purchases||0),invoices:Number(x.invoices||0)}));
db.payments=db.payments.map(x=>({...x,id:x.id??Date.now()+Math.random(),type:x.type==='weekly'?'weekly':'daily',date:String(x.date||x.payDate||localDate()),payDate:String(x.payDate||x.date||localDate()),weekStart:x.weekStart?String(x.weekStart):'',weekEnd:x.weekEnd?String(x.weekEnd):'',empId:Number(x.empId),amount:Number(x.amount||0),note:String(x.note||'')}));
db.abuFadi=db.abuFadi.map(x=>({...x,id:x.id??Date.now()+Math.random(),amount:Number(x.amount||0)}));
db.monthlyBills=db.monthlyBills.map(x=>({...x,id:x.id??Date.now()+Math.random(),month:String(x.month||''),type:String(x.type||'other'),amount:Number(x.amount||0),paid:x.paid!==false,note:String(x.note||'')}));
db.attendance=db.attendance.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),empId:Number(x.empId),status:x.status||'present'}));
db.advances=db.advances.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),empId:Number(x.empId),amount:Number(x.amount||0),note:String(x.note||'')}));
db.inventory=db.inventory.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),qty:Number(x.qty||0),price:Number(x.price||0),used:Number(x.used||0),min:Number(x.min||0)}));
db.suppliers=db.suppliers.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),invoice:String(x.invoice||''),amount:Number(x.amount||0),paid:Number(x.paid||0),date:String(x.date||localDate())}));
db.cash=db.cash.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),opening:Number(x.opening||0),actual:Number(x.actual||0)}));
db.expenseItems=Array.isArray(db.expenseItems)?db.expenseItems.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),defaultAmount:Number(x.defaultAmount||0)})):[];
db.purchaseItems=Array.isArray(db.purchaseItems)?db.purchaseItems.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),defaultAmount:Number(x.defaultAmount||0)})):[];
db.expenses=db.expenses.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||''),itemId:x.itemId??null,itemName:String(x.itemName||x.note||'غير مصنف'),qty:Number(x.qty||1)}));
db.purchases=db.purchases.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||''),itemId:x.itemId??null,itemName:String(x.itemName||x.note||'غير مصنف'),qty:Number(x.qty||1)}));
function save(){localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(SYNC_LOCAL_MODIFIED_KEY,new Date().toISOString());queueCloudSave()}
const SYNC_KEY='talatShamaliSyncV1';
const SYNC_LOCAL_MODIFIED_KEY='talatShamaliLocalModifiedV1';
const SYNC_CLOUD_UPDATED_KEY='talatShamaliCloudUpdatedV1';
let cloudTimer=null, syncBusy=false;
function syncConfig(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||'{}')}catch(e){return {}}}
function saveSyncSettings(){const cfg={url:$("syncUrl").value.trim().replace(/\/$/,''),key:$("syncKey").value.trim(),id:$("syncId").value.trim()};if(!cfg.url||!cfg.key||!cfg.id){alert('أدخل رابط Supabase والمفتاح ورمز المزامنة');return}localStorage.setItem(SYNC_KEY,JSON.stringify(cfg));setSyncStatus('☁️ تم حفظ الإعدادات — جاري تحميل البيانات...');syncNow(false)}
function setSyncStatus(t){if($("syncStatus"))$("syncStatus").textContent=t}
function cloudHeaders(cfg){return {'apikey':cfg.key,'Authorization':'Bearer '+cfg.key,'Content-Type':'application/json','Prefer':'return=representation'}}
function localHasData(){return Object.values(db).some(v=>Array.isArray(v)&&v.length)}
function markCloudUpdated(ts){if(ts)localStorage.setItem(SYNC_CLOUD_UPDATED_KEY,ts)}
async function syncNow(push=false){
 const cfg=syncConfig(); if(!cfg.url||!cfg.key||!cfg.id){setSyncStatus('المزامنة غير مفعلة');return}
 if(syncBusy)return; syncBusy=true;
 try{
  const h=cloudHeaders(cfg);
  if(push){
   const now=new Date().toISOString();
   const r=await fetch(cfg.url+'/rest/v1/cafe_sync',{method:'POST',headers:{...h,'Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id:cfg.id,data:db,updated_at:now})});
   if(!r.ok)throw new Error('push');
   markCloudUpdated(now); localStorage.setItem(SYNC_LOCAL_MODIFIED_KEY,now);
   setSyncStatus('☁️ محفوظ ومتزامن — '+new Date(now).toLocaleTimeString('ar-JO'));
  }else{
   const r=await fetch(cfg.url+'/rest/v1/cafe_sync?id=eq.'+encodeURIComponent(cfg.id)+'&select=data,updated_at',{headers:h});
   if(!r.ok)throw new Error('fetch');
   const rows=await r.json();
   if(rows[0]?.data){
    const cloudTs=rows[0].updated_at||'';
    const localTs=localStorage.getItem(SYNC_LOCAL_MODIFIED_KEY)||'';
    const lastCloud=localStorage.getItem(SYNC_CLOUD_UPDATED_KEY)||'';
    // أول تشغيل على جهاز جديد: إذا لم توجد بيانات محلية، نزّل النسخة السحابية فورًا.
    // إذا كانت هناك بيانات محلية أحدث، لا نستبدلها بصمت.
    if(!localHasData() || !localTs || (cloudTs && cloudTs>localTs && cloudTs!==lastCloud)){
      db=normalizeDb(rows[0].data);
      localStorage.setItem(KEY,JSON.stringify(db));
      localStorage.setItem(SYNC_LOCAL_MODIFIED_KEY,cloudTs||new Date().toISOString());
      markCloudUpdated(cloudTs);
      renderAll();
      setSyncStatus('☁️ تم تحميل جميع البيانات من السحابة');
    }else if(cloudTs && cloudTs>localTs && cloudTs===lastCloud){
      setSyncStatus('☁️ البيانات متزامنة');
    }else{
      setSyncStatus('☁️ البيانات المحلية أحدث — لم يتم استبدالها');
    }
   }else setSyncStatus('☁️ لا توجد بيانات سحابية بعد');
  }
 }catch(e){setSyncStatus('⚠️ تعذر الاتصال بالسحابة — سيتم المحاولة تلقائيًا لاحقًا')}
 finally{syncBusy=false}
}
function queueCloudSave(){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>syncNow(true),500)}
function normalizeDb(raw){raw=raw||{};return {daily:Array.isArray(raw.daily)?raw.daily:[],employees:Array.isArray(raw.employees)?raw.employees:[],payments:Array.isArray(raw.payments)?raw.payments.map(x=>({...x,id:x.id??Date.now()+Math.random(),type:x.type==='weekly'?'weekly':'daily',date:String(x.date||x.payDate||localDate()),payDate:String(x.payDate||x.date||localDate()),weekStart:x.weekStart?String(x.weekStart):'',weekEnd:x.weekEnd?String(x.weekEnd):'',empId:Number(x.empId),amount:Number(x.amount||0),note:String(x.note||'')})):[],archive:Array.isArray(raw.archive)?raw.archive:[],abuFadi:Array.isArray(raw.abuFadi)?raw.abuFadi:[],expenses:Array.isArray(raw.expenses)?raw.expenses.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||''),itemId:x.itemId??null,itemName:String(x.itemName||x.note||'غير مصنف'),qty:Number(x.qty||1)})):[],purchases:Array.isArray(raw.purchases)?raw.purchases.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||''),itemId:x.itemId??null,itemName:String(x.itemName||x.note||'غير مصنف'),qty:Number(x.qty||1)})):[],expenseItems:Array.isArray(raw.expenseItems)?raw.expenseItems.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),defaultAmount:Number(x.defaultAmount||0)})):[],purchaseItems:Array.isArray(raw.purchaseItems)?raw.purchaseItems.map(x=>({...x,id:x.id??Date.now()+Math.random(),name:String(x.name||''),defaultAmount:Number(x.defaultAmount||0)})):[],monthlyBills:Array.isArray(raw.monthlyBills)?raw.monthlyBills:[],attendance:Array.isArray(raw.attendance)?raw.attendance:[],advances:Array.isArray(raw.advances)?raw.advances:[],inventory:Array.isArray(raw.inventory)?raw.inventory:[],suppliers:Array.isArray(raw.suppliers)?raw.suppliers:[],cash:Array.isArray(raw.cash)?raw.cash:[]}}
function loadSyncSettings(doCloud=false){const c=syncConfig();if($("syncUrl")){$("syncUrl").value=c.url||'';$('syncKey').value=c.key||'';$('syncId').value=c.id||''}if(doCloud&&c.url&&c.key&&c.id)syncNow(false)}
// مزامنة تلقائية: عند فتح الموقع ثم كل 10 ثوانٍ، حتى تظهر فواتير الجهاز الآخر دون إدخالها من جديد.
setInterval(()=>{const c=syncConfig();if(c.url&&c.key&&c.id)syncNow(false)},10000);
function toast(msg){const t=$("toast");t.textContent=msg;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',2200)}
function goToday(id){$(id).value=localDate();if(id==='dDate') loadDailyInputs(localDate())}
function scrollToId(id){$(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function dailyFor(date){return db.daily.find(x=>x.date===date)||{date,expenses:0,purchases:0,invoices:0}}
function salaryFor(date){return db.payments.filter(x=>{if(x.type==='weekly')return x.payDate===date;return x.date===date}).reduce((a,x)=>a+Number(x.amount||0),0)}
function netFor(date){const d=dailyFor(date);return Number(d.invoices)-Number(d.expenses)-Number(d.purchases)-salaryFor(date)}
function updateClock(){const now=new Date();const date=new Intl.DateTimeFormat('ar-JO',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(now);const time=new Intl.DateTimeFormat('ar-JO',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);if($("liveClock"))$("liveClock").textContent=`${date} • ${time}`}
setInterval(updateClock,1000);updateClock();
["dashDate","dDate","payDate","abuFadiDate","bulkPayDate","expenseDate","purchaseDate","billMonth","attDate","cashDate","supDate"].forEach(id=>{if($(id))$(id).value=localDate()});$("monthPick").value=localDate().slice(0,7);if($("billMonth"))$("billMonth").value=localDate().slice(0,7);if($("attDate"))$("attDate").value=localDate();if($("cashDate"))$("cashDate").value=localDate();if($("supDate"))$("supDate").value=localDate();

function renderHome(){const date=$("dashDate").value||localDate(),d=dailyFor(date),p=salaryFor(date),b=monthlyBillsTotal(date.slice(0,7)),net=netFor(date)-b;const prev=new Date(date+'T00:00:00');prev.setDate(prev.getDate()-1);const pd=`${prev.getFullYear()}-${String(prev.getMonth()+1).padStart(2,'0')}-${String(prev.getDate()).padStart(2,'0')}`;const prevNet=netFor(pd)-monthlyBillsTotal(pd.slice(0,7));const cash=db.cash.find(x=>x.date===date);const expected=(cash?.opening||0)+d.invoices-(d.expenses+d.purchases+p+b);$("homeHero").innerHTML=`<div class="hero"><div class="hero-title">صافي اليوم • ${esc(date)}</div><div class="hero-value ${net>=0?'ok':'danger-text'}">${money(net)}</div><div class="hero-note">المبيعات − المصاريف − المشتريات − الرواتب − الفواتير الشهرية</div></div>`;$("homeStats").innerHTML=`<div class="card stat"><div class="icon">💵</div><div class="label">مبيعات اليوم</div><div class="big">${money(d.invoices)}</div></div><div class="card stat"><div class="icon">💸</div><div class="label">مصاريف اليوم</div><div class="big">${money(d.expenses+d.purchases+b)}</div></div><div class="card stat"><div class="icon">👥</div><div class="label">الرواتب اليومية</div><div class="big">${money(p)}</div></div><div class="card stat"><div class="icon">📈</div><div class="label">صافي الربح</div><div class="big ${net>=0?'ok':'warn'}">${money(net)}</div></div><div class="card stat"><div class="icon">💰</div><div class="label">رصيد الصندوق المتوقع</div><div class="big">${money(expected)}</div></div><div class="card stat"><div class="icon">↕️</div><div class="label">مقارنة أمس</div><div class="big">${money(net-prevNet)}</div></div>`;const people=db.payments.filter(x=>x.date===date);$("todayEmployees").innerHTML=people.length?`<div class="card"><div class="section-title"><h3 style="margin:0">👥 رواتب الموظفين المسجلة</h3><span class="badge">${people.length} سجل</span></div><div class="table-wrap"><table><tr><th>الموظف</th><th>الأجر</th><th>ملاحظة</th></tr>${people.map(x=>{const e=db.employees.find(e=>e.id===x.empId);return `<tr><td>${esc(e?.name||'محذوف')}</td><td>${money(x.amount)}</td><td>${esc(x.note||'-')}</td></tr>`}).join('')}</table></div></div>`:'';renderWeekChart()}
function renderWeekChart(){const arr=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const ds=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;arr.push({date:ds,net:netFor(ds)})}const max=Math.max(1,...arr.map(x=>Math.abs(x.net)));$("weekChart").innerHTML=arr.map(x=>{const h=Math.max(3,Math.round(Math.abs(x.net)/max*92));const label=x.date.slice(5);return `<div class="bar-col"><div class="bar-val">${x.net.toFixed(0)}</div><div class="bar" style="height:${h}px;opacity:${x.net<0?.55:1}"></div><div class="bar-label">${label}</div></div>`}).join('')}

function loadDailyInputs(date){renderDailyOverview(date||localDate())}
function renderDailyOverview(date){const d=dailyFor(date||localDate()),b=monthlyBillsTotal((date||localDate()).slice(0,7)),pay=salaryFor(date||localDate()),net=Number(d.invoices||0)-Number(d.expenses||0)-Number(d.purchases||0)-pay-b;const el=$("dailyOverview");if(el)el.innerHTML=`<div class="kpi"><div class="l">المبيعات</div><div class="v">${money(d.invoices)}</div></div><div class="kpi"><div class="l">المصاريف</div><div class="v">${money(d.expenses+b)}</div></div><div class="kpi"><div class="l">المشتريات</div><div class="v">${money(d.purchases)}</div></div><div class="kpi"><div class="l">الرواتب</div><div class="v">${money(pay)}</div></div><div class="kpi"><div class="l">الصافي</div><div class="v ${net>=0?'ok':'danger-text'}">${money(net)}</div></div>`}
function renderSales(){const arr=[...db.daily].filter(x=>Number(x.invoices||0)>0).sort((a,b)=>b.date.localeCompare(a.date));const total=arr.reduce((a,x)=>a+Number(x.invoices||0),0);$('salesSummary').innerHTML=`<div class="hero-title">إجمالي المبيعات المسجلة</div><div class="hero-value">${money(total)}</div>`;$('salesTable').innerHTML=arr.length?`<table><tr><th>التاريخ</th><th>المبيعات</th></tr>${arr.map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.invoices)}</td></tr>`).join('')}</table>`:`<div class="empty">لا توجد مبيعات مسجلة بعد</div>`}
$("salesForm").onsubmit=e=>{e.preventDefault();const date=$("salesDate").value||localDate(),amount=Number($("salesAmount").value)||0;const old=db.daily.find(x=>x.date===date);if(old)old.invoices=amount;else db.daily.push({date,expenses:0,purchases:0,invoices:amount});save();e.target.reset();$("salesDate").value=localDate();renderAll();toast('تم حفظ المبيعات ✓')}
$("salesDate").value=localDate();

function billLabel(t){return t==='water'?'تنكات مياه':t==='electricity'?'كهرباء':t==='rent'?'إيجار محل':'أخرى'}
function monthlyBillsFor(m){return db.monthlyBills.filter(x=>x.month===m)}
function monthlyBillsTotal(m){return monthlyBillsFor(m).reduce((a,x)=>a+Number(x.amount||0),0)}
function renderBills(){const m=$('billMonth')?.value||localDate().slice(0,7);const arr=[...db.monthlyBills].sort((a,b)=>b.month.localeCompare(a.month)||b.id-a.id);const total=arr.filter(x=>x.month===m).reduce((a,x)=>a+Number(x.amount||0),0);$('billSummary').innerHTML=`<div class="card stat"><div class="label">تنكات مياه</div><div class="big">${money(arr.filter(x=>x.month===m&&x.type==='water').reduce((a,x)=>a+x.amount,0))}</div></div><div class="card stat"><div class="label">كهرباء</div><div class="big">${money(arr.filter(x=>x.month===m&&x.type==='electricity').reduce((a,x)=>a+x.amount,0))}</div></div><div class="card stat"><div class="label">إيجار المحل</div><div class="big">${money(arr.filter(x=>x.month===m&&x.type==='rent').reduce((a,x)=>a+x.amount,0))}</div></div><div class="card stat"><div class="label">إجمالي فواتير الشهر</div><div class="big">${money(total)}</div></div>`;$('billTable').innerHTML=arr.length?`<table><tr><th>الشهر</th><th>الفاتورة</th><th>المبلغ</th><th>الحالة</th><th>ملاحظة</th><th></th></tr>${arr.map(x=>`<tr><td>${esc(x.month)}</td><td>${billLabel(x.type)}</td><td>${money(x.amount)}</td><td>${x.paid?'مدفوعة':'غير مدفوعة'}</td><td>${esc(x.note||'-')}</td><td><button class="btn danger" onclick="deleteBill(${x.id})">حذف</button></td></tr>`).join('')}</table>`:`<div class="empty">لا توجد فواتير شهرية بعد</div>`}
$('billForm').onsubmit=e=>{e.preventDefault();db.monthlyBills.push({id:Date.now()+Math.random(),month:$('billMonth').value,type:$('billType').value,amount:Number($('billAmount').value)||0,paid:$('billPaid').value==='true',note:$('billNote').value.trim()});save();e.target.reset();$('billMonth').value=localDate().slice(0,7);renderAll();toast('تم حفظ الفاتورة الشهرية ✓')};function deleteBill(id){if(confirm('حذف الفاتورة؟')){db.monthlyBills=db.monthlyBills.filter(x=>x.id!==id);save();renderAll()}}
function saveAttendanceAdvance(){const date=$('attDate').value||localDate(),empId=Number($('attEmp').value),status=$('attStatus').value,amount=Number($('advanceAmount').value)||0;if(!empId)return;if(db.attendance.some(x=>x.date===date&&Number(x.empId)===empId))db.attendance.find(x=>x.date===date&&Number(x.empId)===empId).status=status;else db.attendance.push({id:Date.now()+Math.random(),date,empId,status});if(amount>0)db.advances.push({id:Date.now()+Math.random(),date,empId,amount,note:$('advanceNote').value.trim()});save();renderAll();toast('تم حفظ الحضور والسلفة ✓')}
function renderAttendance(){const active=db.employees.filter(e=>e.status!=='inactive');$('attEmp').innerHTML=active.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');const rows=[...db.attendance].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,50).map(x=>{const e=db.employees.find(e=>e.id===x.empId);return `<tr><td>${x.date}</td><td>${esc(e?.name||'محذوف')}</td><td>${x.status==='present'?'حاضر':x.status==='absent'?'غائب':'إجازة'}</td></tr>`}).join('');$('attendanceTable').innerHTML=rows?`<table><tr><th>التاريخ</th><th>الموظف</th><th>الحالة</th></tr>${rows}</table>`:`<div class="empty">لا توجد سجلات حضور بعد</div>`}
function salaryTotals(){const now=new Date(),m=localDate().slice(0,7),y=String(now.getFullYear());return {week:db.payments.filter(x=>{const d=x.date||x.payDate;return d>=weekStart(localDate())&&d<=weekEnd(localDate())}).reduce((a,x)=>a+x.amount,0),month:db.payments.filter(x=>monthOf(x.date||x.payDate)===m).reduce((a,x)=>a+x.amount,0),year:db.payments.filter(x=>String(x.date||x.payDate).startsWith(y+'-')).reduce((a,x)=>a+x.amount,0)}}
function renderCustomReport(){const f=$('rangeFrom').value,t=$('rangeTo').value;if(!f||!t)return;let sales=0,exp=0,pur=0,sal=0;db.daily.filter(x=>x.date>=f&&x.date<=t).forEach(x=>{sales+=x.invoices;exp+=x.expenses;pur+=x.purchases});exp+=db.expenses.filter(x=>x.date>=f&&x.date<=t).reduce((a,x)=>a+x.amount,0);pur+=db.purchases.filter(x=>x.date>=f&&x.date<=t).reduce((a,x)=>a+x.amount,0);sal=db.payments.filter(x=>(x.date||x.payDate)>=f&&(x.date||x.payDate)<=t).reduce((a,x)=>a+x.amount,0);const bills=db.monthlyBills.filter(x=>x.month>=f.slice(0,7)&&x.month<=t.slice(0,7)).reduce((a,x)=>a+x.amount,0);exp+=bills;const profit=sales-exp-pur-sal;$('customReport').innerHTML=`<div class="grid"><div class="card stat"><div class="label">المبيعات</div><div class="big">${money(sales)}</div></div><div class="card stat"><div class="label">المصاريف + الفواتير الشهرية</div><div class="big">${money(exp)}</div></div><div class="card stat"><div class="label">المشتريات</div><div class="big">${money(pur)}</div></div><div class="card stat"><div class="label">الرواتب</div><div class="big">${money(sal)}</div></div><div class="card stat"><div class="label">صافي الربح</div><div class="big ${profit>=0?'ok':'warn'}">${money(profit)}</div></div></div>`}
function saveCash(){const date=$('cashDate').value||localDate(),opening=Number($('cashOpening').value)||0,actual=Number($('cashActual').value)||0;const old=db.cash.find(x=>x.date===date);const d=dailyFor(date),out=Number(d.expenses)+Number(d.purchases)+salaryFor(date)+monthlyBillsTotal(date.slice(0,7));const expected=opening+Number(d.invoices)-out;if(old)Object.assign(old,{opening,actual});else db.cash.push({id:Date.now()+Math.random(),date,opening,actual});save();renderAll();$('cashBox').innerHTML=`<div class="kpi-row"><div class="kpi"><div class="l">المتوقع</div><div class="v">${money(expected)}</div></div><div class="kpi"><div class="l">الفعلي</div><div class="v">${money(actual)}</div></div><div class="kpi"><div class="l">الفرق</div><div class="v ${actual-expected===0?'ok':'warn'}">${money(actual-expected)}</div></div></div>`}
function renderInventory(){const rows=db.inventory.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${x.used}</td><td>${x.min}</td><td>${x.qty<=x.min?'<span class="badge">⚠️ منخفض</span>':'<span class="badge">جيد</span>'}</td></tr>`).join('');$('invTable').innerHTML=rows?`<table><tr><th>الصنف</th><th>الكمية</th><th>سعر الشراء</th><th>المستخدم</th><th>حد التنبيه</th><th>الحالة</th></tr>${rows}</table>`:`<div class="empty">لا توجد أصناف</div>`}
$('invForm').onsubmit=e=>{e.preventDefault();db.inventory.push({id:Date.now()+Math.random(),name:$('invName').value.trim(),qty:Number($('invQty').value)||0,price:Number($('invPrice').value)||0,used:Number($('invUsed').value)||0,min:Number($('invMin').value)||0});save();e.target.reset();renderAll();toast('تم حفظ الصنف ✓')};$('supplierForm').onsubmit=e=>{e.preventDefault();db.suppliers.push({id:Date.now()+Math.random(),name:$('supName').value.trim(),invoice:$('supInvoice').value.trim(),amount:Number($('supAmount').value)||0,paid:Number($('supPaid').value)||0,date:$('supDate').value||localDate()});save();e.target.reset();$('supDate').value=localDate();renderAll();toast('تم حفظ المورد ✓')};function renderSuppliers(){const rows=db.suppliers.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.name)}</td><td>${esc(x.invoice||'-')}</td><td>${money(x.amount)}</td><td>${money(x.paid)}</td><td>${money(x.amount-x.paid)}</td></tr>`).join('');$('supplierTable').innerHTML=rows?`<table><tr><th>التاريخ</th><th>المورد</th><th>الفاتورة</th><th>المبلغ</th><th>المدفوع</th><th>المتبقي</th></tr>${rows}</table>`:`<div class="empty">لا توجد فواتير موردين</div>`}
function viewArchive(m){const x=monthData(m);alert(`أرشيف ${m}\nالمبيعات: ${money(x.invoices)}\nالمصاريف: ${money(x.expenses)}\nالمشتريات: ${money(x.purchases)}\nالرواتب: ${money(x.salaries)}\nالفواتير الشهرية: ${money(monthlyBillsTotal(m))}\nصافي الربح: ${money(x.profitWithInvoices)}`)}
function exportExcel(){if(typeof XLSX==='undefined'){alert('مكتبة Excel لم تُحمّل. تأكد من اتصال الإنترنت ثم حاول مرة أخرى.');return}const wb=XLSX.utils.book_new();const rows=(arr,headers,mapper)=>[headers,...arr.map(mapper)];const summary=[['التقرير','كافيه طلة الشمالي'],['تاريخ التصدير',new Date().toLocaleString('ar-JO')],['إجمالي المبيعات',db.daily.reduce((a,x)=>a+x.invoices,0)],['إجمالي المصاريف',db.daily.reduce((a,x)=>a+x.expenses,0)+db.expenses.reduce((a,x)=>a+x.amount,0)+db.monthlyBills.reduce((a,x)=>a+x.amount,0)],['إجمالي المشتريات',db.daily.reduce((a,x)=>a+x.purchases,0)+db.purchases.reduce((a,x)=>a+x.amount,0)],['إجمالي الرواتب',db.payments.reduce((a,x)=>a+x.amount,0)],['صافي الربح',db.daily.reduce((a,x)=>a+x.invoices-x.expenses-x.purchases,0)-db.expenses.reduce((a,x)=>a+x.amount,0)-db.purchases.reduce((a,x)=>a+x.amount,0)-db.monthlyBills.reduce((a,x)=>a+x.amount,0)-db.payments.reduce((a,x)=>a+x.amount,0)]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),'الملخص');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.daily,['التاريخ','المبيعات','المصاريف','المشتريات','الرواتب','الصافي'],x=>[x.date,x.invoices,x.expenses,x.purchases,salaryFor(x.date),netFor(x.date)])),'المبيعات');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.expenses,['التاريخ','المبلغ','البيان'],x=>[x.date,x.amount,x.note])), 'المصاريف');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.purchases,['التاريخ','المبلغ','البيان'],x=>[x.date,x.amount,x.note])), 'المشتريات');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.payments,['التاريخ','الموظف','المبلغ','الملاحظة'],x=>[x.date,db.employees.find(e=>e.id===x.empId)?.name||'محذوف',x.amount,x.note])), 'الموظفين والرواتب');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.monthlyBills,['الشهر','الفاتورة','المبلغ','الحالة','الملاحظة'],x=>[x.month,billLabel(x.type),x.amount,x.paid?'مدفوعة':'غير مدفوعة',x.note])), 'الفواتير الشهرية');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.inventory,['الصنف','الكمية','سعر الشراء','المستخدم','حد التنبيه'],x=>[x.name,x.qty,x.price,x.used,x.min])), 'المخزون');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.suppliers,['التاريخ','المورد','الفاتورة','المبلغ','المدفوع','المتبقي'],x=>[x.date,x.name,x.invoice,x.amount,x.paid,x.amount-x.paid])), 'الموردون');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows(db.archive,['الشهر','المبيعات','المصاريف','المشتريات','الرواتب','الربح'],x=>[x.month,x.invoices,x.expenses,x.purchases,x.salaries,x.profitWithInvoices])), 'الأرشيف');XLSX.writeFile(wb,`talat-shamali-report-${localDate()}.xlsx`);toast('تم تصدير تقرير Excel مرتب ✓')}
function exportBackup(){const data={...db,exportedAt:new Date().toISOString(),app:'كافيه طلة الشمالي'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`talat-shamali-backup-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم إنشاء النسخة الاحتياطية ✓')}
$("importFile").addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!Array.isArray(x.daily)||!Array.isArray(x.employees)||!Array.isArray(x.payments)){throw new Error('invalid')}if(confirm('سيتم استبدال البيانات الحالية بالنسخة المختارة. هل أنت متأكد؟')){db=normalizeDb(x);save();renderAll();toast('تم استيراد النسخة ✓')}}catch(err){alert('ملف النسخة الاحتياطية غير صالح')}};reader.readAsText(file);e.target.value=''})
function resetAll(){if(confirm('سيتم حذف كل بيانات الموقع نهائيًا من هذا الجهاز. هل أخذت نسخة احتياطية؟')){localStorage.removeItem(KEY);location.reload()}}

const LOGIN_USER='Mohammed',LOGIN_PASS='jasser';
function applyLogin(){$("loginScreen").style.display=localStorage.getItem('talatLogged')==='1'?'none':'flex'}
$("loginForm").onsubmit=e=>{e.preventDefault();if($("loginUser").value===LOGIN_USER&&$("loginPass").value===LOGIN_PASS){localStorage.setItem('talatLogged','1');$("loginError").style.display='none';applyLogin()}else $("loginError").style.display='block'};
function logout(){localStorage.removeItem('talatLogged');applyLogin()}
function renderAll(){autoArchiveCompletedMonths();renderHome();renderDaily();renderSales();renderSalaries();renderAbuFadi();renderLedgerItems('expenses');renderLedgerItems('purchases');renderEntries('expenses');renderEntries('purchases');renderMonth();renderAnnual();renderArchive();renderDailyArchive();renderBills();renderInventory();renderSuppliers();renderDailyOverview(localDate());}
$("dashDate").addEventListener('change',renderHome);$("monthPick").addEventListener('change',renderMonth);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$("installAppBtn").style.display='block'});
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$("installAppBtn").style.display='none'}else toast('من قائمة المتصفح اختر إضافة إلى الشاشة الرئيسية')}
window.addEventListener('appinstalled',()=>$("installAppBtn").style.display='none');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}
applyLogin();loadSyncSettings(true);renderAll();loadDailyInputs(localDate());
