
const KEY="talatShamaliAccountingV3";
const empty={daily:[],employees:[],payments:[],archive:[],abuFadi:[],expenses:[],purchases:[]};
let db=loadDb();
let editingEmployeeId=null;
let deferredInstallPrompt=null;
const $=id=>document.getElementById(id);
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=n=>Number(n||0).toFixed(2)+" JD";
const monthOf=d=>String(d||"").slice(0,7);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadDb(){try{const raw=JSON.parse(localStorage.getItem(KEY)||"null")||empty;return {daily:Array.isArray(raw.daily)?raw.daily:[],employees:Array.isArray(raw.employees)?raw.employees:[],payments:Array.isArray(raw.payments)?raw.payments:[],archive:Array.isArray(raw.archive)?raw.archive:[],abuFadi:Array.isArray(raw.abuFadi)?raw.abuFadi:[],expenses:Array.isArray(raw.expenses)?raw.expenses:[],purchases:Array.isArray(raw.purchases)?raw.purchases:[]};}catch(e){return {...empty}}}
db.employees=db.employees.map(e=>({...e,id:e.id??Date.now()+Math.random(),name:String(e.name||''),job:String(e.job||''),salary:Number(e.salary||0),status:e.status||'active'}));
db.daily=db.daily.map(x=>({...x,expenses:Number(x.expenses||0),purchases:Number(x.purchases||0),invoices:Number(x.invoices||0)}));
db.payments=db.payments.map(x=>({...x,id:x.id??Date.now()+Math.random(),type:x.type==='weekly'?'weekly':'daily',date:String(x.date||x.payDate||localDate()),payDate:String(x.payDate||x.date||localDate()),weekStart:x.weekStart?String(x.weekStart):'',weekEnd:x.weekEnd?String(x.weekEnd):'',empId:Number(x.empId),amount:Number(x.amount||0),note:String(x.note||'')}));
db.abuFadi=db.abuFadi.map(x=>({...x,id:x.id??Date.now()+Math.random(),amount:Number(x.amount||0)}));
db.expenses=db.expenses.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||'')}));
db.purchases=db.purchases.map(x=>({...x,id:x.id??Date.now()+Math.random(),date:String(x.date||localDate()),amount:Number(x.amount||0),note:String(x.note||'')}));
function save(){localStorage.setItem(KEY,JSON.stringify(db)); queueCloudSave()}
const SYNC_KEY='talatShamaliSyncV1';
let cloudTimer=null;
function syncConfig(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||'{}')}catch(e){return {}}}
function saveSyncSettings(){const cfg={url:$("syncUrl").value.trim().replace(/\/$/,''),key:$("syncKey").value.trim(),id:$("syncId").value.trim()};if(!cfg.url||!cfg.key||!cfg.id){alert('أدخل رابط Supabase والمفتاح ورمز المزامنة');return}localStorage.setItem(SYNC_KEY,JSON.stringify(cfg));setSyncStatus('تم حفظ إعدادات المزامنة. جاري الرفع...');syncNow(true)}
function setSyncStatus(t){if($("syncStatus"))$("syncStatus").textContent=t}
function cloudHeaders(cfg){return {'apikey':cfg.key,'Authorization':'Bearer '+cfg.key,'Content-Type':'application/json','Prefer':'return=representation'}}
async function syncNow(push=false){const cfg=syncConfig();if(!cfg.url||!cfg.key||!cfg.id){setSyncStatus('المزامنة غير مفعلة');return}try{const h=cloudHeaders(cfg);if(push){await fetch(cfg.url+'/rest/v1/cafe_sync',{method:'POST',headers:{...h,'Prefer':'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id:cfg.id,data:db,updated_at:new Date().toISOString()})});setSyncStatus('☁️ تم حفظ البيانات على السحابة')}else{const r=await fetch(cfg.url+'/rest/v1/cafe_sync?id=eq.'+encodeURIComponent(cfg.id)+'&select=data,updated_at',{headers:h});if(!r.ok)throw new Error('fetch');const rows=await r.json();if(rows[0]?.data){db=normalizeDb(rows[0].data);localStorage.setItem(KEY,JSON.stringify(db));renderAll();setSyncStatus('☁️ تم تحميل آخر نسخة')}else setSyncStatus('لا توجد نسخة سحابية بعد')}}catch(e){setSyncStatus('تعذر الاتصال بالسحابة — تحقق من الإعدادات')}}
function queueCloudSave(){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>syncNow(true),700)}
function normalizeDb(raw){raw=raw||{};return {daily:Array.isArray(raw.daily)?raw.daily:[],employees:Array.isArray(raw.employees)?raw.employees:[],payments:Array.isArray(raw.payments)?raw.payments.map(x=>({...x,id:x.id??Date.now()+Math.random(),type:x.type==='weekly'?'weekly':'daily',date:String(x.date||x.payDate||localDate()),payDate:String(x.payDate||x.date||localDate()),weekStart:x.weekStart?String(x.weekStart):'',weekEnd:x.weekEnd?String(x.weekEnd):'',empId:Number(x.empId),amount:Number(x.amount||0),note:String(x.note||'')})):[],archive:Array.isArray(raw.archive)?raw.archive:[],abuFadi:Array.isArray(raw.abuFadi)?raw.abuFadi:[],expenses:Array.isArray(raw.expenses)?raw.expenses:[],purchases:Array.isArray(raw.purchases)?raw.purchases:[]}}
function loadSyncSettings(doCloud=false){const c=syncConfig();if($("syncUrl")){$("syncUrl").value=c.url||'';$('syncKey').value=c.key||'';$('syncId').value=c.id||''}if(doCloud&&c.url&&c.key&&c.id)syncNow(false)}
function toast(msg){const t=$("toast");t.textContent=msg;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',2200)}
function goToday(id){$(id).value=localDate();if(id==='dDate') loadDailyInputs(localDate())}
function scrollToId(id){$(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function dailyFor(date){return db.daily.find(x=>x.date===date)||{date,expenses:0,purchases:0,invoices:0}}
function salaryFor(date){return db.payments.filter(x=>{if(x.type==='weekly')return x.payDate===date;return x.date===date}).reduce((a,x)=>a+Number(x.amount||0),0)}
function netFor(date){const d=dailyFor(date);return Number(d.invoices)-Number(d.expenses)-Number(d.purchases)-salaryFor(date)}
function updateClock(){const now=new Date();const date=new Intl.DateTimeFormat('ar-JO',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(now);const time=new Intl.DateTimeFormat('ar-JO',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);if($("liveClock"))$("liveClock").textContent=`${date} • ${time}`}
setInterval(updateClock,1000);updateClock();
["dashDate","dDate","payDate","abuFadiDate","bulkPayDate","expenseDate","purchaseDate"].forEach(id=>{if($(id))$(id).value=localDate()});$("monthPick").value=localDate().slice(0,7);

function renderHome(){const date=$("dashDate").value||localDate(),d=dailyFor(date),p=salaryFor(date),net=netFor(date);$("homeHero").innerHTML=`<div class="hero"><div class="hero-title">صافي اليوم • ${esc(date)}</div><div class="hero-value ${net>=0?'ok':'danger-text'}">${money(net)}</div><div class="hero-note">الفواتير − المصاريف − المشتريات − أجور الموظفين</div></div>`;$("homeStats").innerHTML=`<div class="card stat"><div class="icon">💵</div><div class="label">الفواتير / المبيعات</div><div class="big">${money(d.invoices)}</div></div><div class="card stat"><div class="icon">🛒</div><div class="label">المشتريات</div><div class="big">${money(d.purchases)}</div></div><div class="card stat"><div class="icon">💸</div><div class="label">المصاريف</div><div class="big">${money(d.expenses)}</div></div><div class="card stat"><div class="icon">👥</div><div class="label">أجور الأسبوع المسجلة</div><div class="big">${money(p)}</div></div>`;const people=db.payments.filter(x=>x.date===date);$("todayEmployees").innerHTML=people.length?`<div class="card"><div class="section-title"><h3 style="margin:0">👥 رواتب الموظفين المسجلة</h3><span class="badge">${people.length} سجل</span></div><div class="table-wrap"><table><tr><th>الموظف</th><th>الأجر</th><th>ملاحظة</th></tr>${people.map(x=>{const e=db.employees.find(e=>e.id===x.empId);return `<tr><td>${esc(e?.name||'محذوف')}</td><td>${money(x.amount)}</td><td>${esc(x.note||'-')}</td></tr>`}).join('')}</table></div></div>`:'';renderWeekChart()}
function renderWeekChart(){const arr=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const ds=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;arr.push({date:ds,net:netFor(ds)})}const max=Math.max(1,...arr.map(x=>Math.abs(x.net)));$("weekChart").innerHTML=arr.map(x=>{const h=Math.max(3,Math.round(Math.abs(x.net)/max*92));const label=x.date.slice(5);return `<div class="bar-col"><div class="bar-val">${x.net.toFixed(0)}</div><div class="bar" style="height:${h}px;opacity:${x.net<0?.55:1}"></div><div class="bar-label">${label}</div></div>`}).join('')}

function loadDailyInputs(date){const d=dailyFor(date);$("dExpInput").value=d.expenses||0;$("dPurInput").value=d.purchases||0;$("dInvInput").value=d.invoices||0;updateDailyPreview()}
function updateDailyPreview(){const date=$("dDate").value||localDate();const exp=Number($("dExpInput").value||0),pur=Number($("dPurInput").value||0),inv=Number($("dInvInput").value||0),pay=salaryFor(date),pre=inv-exp-pur,net=pre-pay;$("dailyPreview").textContent=money(pre);$("dailyPayPreview").textContent=money(pay);$("dailyNetPreview").textContent=money(net);$("dailyNetPreview").className='v '+(net>=0?'ok':'danger-text')}
["dDate","dExpInput","dPurInput","dInvInput"].forEach(id=>$(id)?.addEventListener('input',updateDailyPreview));$("dDate")?.addEventListener('change',e=>loadDailyInputs(e.target.value));
$("dailyForm").onsubmit=e=>{e.preventDefault();const date=$("dDate").value;if(!date)return;const obj={date,expenses:Number($("dExpInput").value)||0,purchases:Number($("dPurInput").value)||0,invoices:Number($("dInvInput").value)||0};const old=db.daily.find(x=>x.date===date);if(old)Object.assign(old,obj);else db.daily.push(obj);save();renderAll();toast('تم حفظ حساب اليوم ✓')}
function renderDaily(){const rows=[...db.daily].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.expenses)}</td><td>${money(x.purchases)}</td><td>${money(x.invoices)}</td><td>${money(salaryFor(x.date))}</td><td class="${netFor(x.date)>=0?'ok':'warn'}">${money(netFor(x.date))}</td><td><button class="btn danger" onclick="deleteDaily('${esc(x.date)}')">حذف</button></td></tr>`).join('');$("dailyTable").innerHTML=rows?`<table><tr><th>التاريخ</th><th>المصاريف</th><th>المشتريات</th><th>الفواتير</th><th>الأجور</th><th>الصافي</th><th></th></tr>${rows}</table>`:`<div class="empty">لا توجد حسابات مسجلة بعد</div>`}
function deleteDaily(date){if(confirm('حذف حساب هذا اليوم؟')){db.daily=db.daily.filter(x=>x.date!==date);save();renderAll();toast('تم الحذف')}}

$("empForm").onsubmit=e=>{e.preventDefault();const name=$("empName").value.trim();if(!name)return;const data={name,job:$("empJob").value.trim(),salary:Number($("empSalary").value)||0,status:$("empStatus").value};if(editingEmployeeId!==null){const emp=db.employees.find(x=>x.id===editingEmployeeId);if(emp)Object.assign(emp,data);editingEmployeeId=null;$("empSubmit").textContent='➕ إضافة موظف';$("empCancel").style.display='none';toast('تم تحديث الموظف ✓')}else{db.employees.push({id:Date.now()+Math.random(),...data});toast('تمت إضافة الموظف ✓')}e.target.reset();$("empSalary").value=0;$("empStatus").value='active';save();renderAll()}
function editEmployee(id){const e=db.employees.find(x=>x.id===id);if(!e)return;editingEmployeeId=id;$("empName").value=e.name;$("empJob").value=e.job;$("empSalary").value=e.salary;$("empStatus").value=e.status;$("empSubmit").textContent='💾 حفظ التعديل';$("empCancel").style.display='inline-block';scrollToId('empForm')}
$("empCancel").onclick=()=>{editingEmployeeId=null;$("empForm").reset();$("empSalary").value=0;$("empStatus").value='active';$("empSubmit").textContent='➕ إضافة موظف';$("empCancel").style.display='none'};
function deleteEmployee(id){if(confirm('حذف الموظف؟ السجلات القديمة للأجور ستبقى محفوظة.')){db.employees=db.employees.filter(x=>x.id!==id);save();renderAll();toast('تم حذف الموظف')}}
function weekStart(date){const d=new Date((date||localDate())+'T00:00:00');const day=d.getDay();const diff=day===0?-6:1-day;d.setDate(d.getDate()+diff);return d.toISOString().slice(0,10)}
function weekEnd(date){const d=new Date(weekStart(date)+'T00:00:00');d.setDate(d.getDate()+6);return d.toISOString().slice(0,10)}
function weekLabel(date){return `${weekStart(date)} → ${weekEnd(date)}`}
function existingWeeklyPayTotal(start,empId){return db.payments.filter(x=>x.type==='weekly'&&x.weekStart===start&&Number(x.empId)===Number(empId)).reduce((a,x)=>a+Number(x.amount||0),0)}
function renderSalaries(){const active=db.employees.filter(e=>e.status!=='inactive').length,totalWeekly=db.employees.filter(e=>e.status!=='inactive').reduce((a,e)=>a+Number(e.salary||0),0),totalPayments=db.payments.reduce((a,p)=>a+Number(p.amount||0),0);$("empSummary").innerHTML=`<div class="card stat"><div class="icon">👥</div><div class="label">كل الموظفين</div><div class="big">${db.employees.length}</div></div><div class="card stat"><div class="icon">🟢</div><div class="label">النشطون</div><div class="big">${active}</div></div><div class="card stat"><div class="icon">💰</div><div class="label">إجمالي الراتب الأسبوعي المتوقع</div><div class="big">${money(totalWeekly)}</div></div><div class="card stat"><div class="icon">📒</div><div class="label">إجمالي الرواتب المسجلة</div><div class="big">${money(totalPayments)}</div></div>`;const rows=db.employees.map(e=>`<tr><td><b>${esc(e.name)}</b><div class="muted" style="font-size:9px">${esc(e.job||'بدون وظيفة')}</div></td><td>${money(e.salary)}</td><td><span class="badge">${e.status==='inactive'?'غير نشط':'نشط'}</span></td><td><div class="actions"><button class="btn" onclick="editEmployee(${e.id})">تعديل</button><button class="btn danger" onclick="deleteEmployee(${e.id})">حذف</button></div></td></tr>`).join('');$("empTable").innerHTML=rows?`<div class="table-wrap"><table><tr><th>الموظف</th><th>الراتب الأسبوعي</th><th>الحالة</th><th></th></tr>${rows}</table></div>`:`<div class="empty">أضف أول موظف ثم سجّل راتبه الأسبوعي</div>`;renderBulkPay();renderPayTable()}
function renderBulkPay(){const date=$("bulkPayDate").value||localDate(),start=weekStart(date),end=weekEnd(date);$("weekRange").textContent=`الأسبوع: ${start} → ${end} • يمكنك تغيير المبلغ يدويًا قبل الحفظ`;const active=db.employees.filter(e=>e.status!=='inactive');$("bulkPayList").innerHTML=active.length?active.map(e=>{const ex=existingWeeklyPayTotal(start,e.id);const val=ex>0?ex:Number(e.salary||0);return `<div class="pay-row"><div><div class="pay-name">${esc(e.name)}</div><div class="pay-job">${esc(e.job||'')}</div></div><input class="bulk-amount" data-id="${e.id}" type="number" min="0" step=".01" value="${val}" placeholder="المبلغ اليدوي"><div class="check"><input class="bulk-check" data-id="${e.id}" type="checkbox" ${ex>0?'checked':''}></div></div>`}).join(''):`<div class="empty">لا يوجد موظفون نشطون</div>`;updateBulkTotals()}
function updateBulkTotals(){const rows=[...document.querySelectorAll('.pay-row')];let total=0,checked=0;rows.forEach(r=>{const amount=Number(r.querySelector('.bulk-amount')?.value||0);const c=r.querySelector('.bulk-check')?.checked;if(c){total+=amount;checked++}});$("bulkCount").textContent=rows.length;$("bulkTotal").textContent=money(total);$("bulkRecorded").textContent=checked}
$("bulkPayDate").addEventListener('change',renderBulkPay);document.addEventListener('input',e=>{if(e.target.classList.contains('bulk-amount'))updateBulkTotals()});document.addEventListener('change',e=>{if(e.target.classList.contains('bulk-check'))updateBulkTotals()});
function saveBulkWages(){const selected=$("bulkPayDate").value||localDate(),start=weekStart(selected),end=weekEnd(selected),payDate=end;let changed=0;document.querySelectorAll('.pay-row').forEach(row=>{const id=Number(row.querySelector('.bulk-amount').dataset.id);const checked=row.querySelector('.bulk-check').checked;const amount=Number(row.querySelector('.bulk-amount').value)||0;const indexes=[];db.payments.forEach((p,i)=>{if(p.type==='weekly'&&p.weekStart===start&&Number(p.empId)===id)indexes.push(i)});if(checked){if(indexes.length){db.payments[indexes[0]].amount=amount;db.payments[indexes[0]].weekEnd=end;db.payments[indexes[0]].payDate=payDate;db.payments[indexes[0]].note='راتب أسبوعي';for(let i=indexes.length-1;i>=1;i--)db.payments.splice(indexes[i],1)}else db.payments.push({id:Date.now()+Math.random(),type:'weekly',date:payDate,payDate,weekStart:start,weekEnd:end,empId:id,amount,note:'راتب أسبوعي'});changed++}else if(indexes.length){for(let i=indexes.length-1;i>=0;i--)db.payments.splice(indexes[i],1);changed++}});save();renderAll();toast(`تم حفظ رواتب ${changed} موظف للأسبوع ✓`)}
$("paySearch").addEventListener('input',renderPayTable);
function renderPayTable(){const q=($("paySearch")?.value||'').trim().toLowerCase();const rows=[...db.payments].sort((a,b)=>(b.payDate||b.date).localeCompare(a.payDate||a.date)||b.id-a.id).filter(x=>{const e=db.employees.find(e=>e.id===x.empId);return !q||(e?.name||'محذوف').toLowerCase().includes(q)}).map(x=>{const e=db.employees.find(e=>e.id===x.empId);const weekly=x.type==='weekly';return `<tr><td>${weekly?esc(x.weekStart+' → '+x.weekEnd):esc(x.date)}</td><td>${esc(e?.name||'محذوف')}</td><td>${money(x.amount)}</td><td>${esc(x.note||'-')}</td><td><button class="btn danger" onclick="deletePayment(${x.id})">حذف</button></td></tr>`}).join('');$("payTable").innerHTML=rows?`<table><tr><th>الأسبوع / التاريخ</th><th>الموظف</th><th>المبلغ</th><th>ملاحظة</th><th></th></tr>${rows}</table>`:`<div class="empty">لا توجد سجلات رواتب</div>`}
function deletePayment(id){if(confirm('حذف سجل الراتب؟')){db.payments=db.payments.filter(x=>x.id!==id);save();renderAll();toast('تم حذف سجل الراتب')}}

$("abuFadiForm").onsubmit=e=>{e.preventDefault();db.abuFadi.push({id:Date.now()+Math.random(),date:$("abuFadiDate").value,amount:Number($("abuFadiAmount").value)||0,note:$("abuFadiNote").value.trim()});save();e.target.reset();$("abuFadiDate").value=localDate();renderAll();toast('تمت إضافة الفاتورة ✓')}
function renderAbuFadi(){const rows=[...db.abuFadi].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.amount)}</td><td>${esc(x.note||'-')}</td><td><button class="btn danger" onclick="deleteAbu(${x.id})">حذف</button></td></tr>`).join('');const total=db.abuFadi.reduce((a,x)=>a+Number(x.amount||0),0);$("abuFadiTotal").innerHTML=`<div class="hero-title">إجمالي فواتير أبو فادي</div><div class="hero-value">${money(total)}</div>`;$("abuFadiTable").innerHTML=rows?`<table><tr><th>التاريخ</th><th>المبلغ</th><th>الملاحظة</th><th></th></tr>${rows}</table>`:`<div class="empty">لا توجد فواتير بعد</div>`}
function deleteAbu(id){if(confirm('حذف الفاتورة؟')){db.abuFadi=db.abuFadi.filter(x=>x.id!==id);save();renderAll();toast('تم الحذف')}}

function renderEntries(type){const arr=db[type]||[], prefix=type==='expenses'?'expense':'purchase';const sorted=[...arr].sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);const total=arr.reduce((a,x)=>a+Number(x.amount||0),0);$(prefix+'Summary').innerHTML=`<div class="hero-title">إجمالي ${type==='expenses'?'المصاريف':'المشتريات'}</div><div class="hero-value">${money(total)}</div>`;$(prefix+'Table').innerHTML=sorted.length?`<table><tr><th>التاريخ</th><th>المبلغ</th><th>البيان</th><th></th></tr>${sorted.map(x=>`<tr><td>${esc(x.date)}</td><td>${money(x.amount)}</td><td>${esc(x.note||'-')}</td><td><button class="btn danger" onclick="deleteEntry('${type}',${x.id})">حذف</button></td></tr>`).join('')}</table>`:`<div class="empty">لا توجد سجلات بعد</div>`}
function deleteEntry(type,id){if(confirm('حذف السجل؟')){db[type]=db[type].filter(x=>x.id!==id);save();renderAll();toast('تم الحذف')}}
$('expenseForm').onsubmit=e=>{e.preventDefault();db.expenses.push({id:Date.now()+Math.random(),date:$('expenseDate').value,amount:Number($('expenseAmount').value)||0,note:$('expenseNote').value.trim()});save();e.target.reset();$('expenseDate').value=localDate();renderAll();toast('تم حفظ المصروف ✓')};
$('purchaseForm').onsubmit=e=>{e.preventDefault();db.purchases.push({id:Date.now()+Math.random(),date:$('purchaseDate').value,amount:Number($('purchaseAmount').value)||0,note:$('purchaseNote').value.trim()});save();e.target.reset();$('purchaseDate').value=localDate();renderAll();toast('تم حفظ المشتريات ✓')};
function totalsForMonth(m){const exp=db.expenses.filter(x=>monthOf(x.date)===m).reduce((a,x)=>a+Number(x.amount||0),0);const pur=db.purchases.filter(x=>monthOf(x.date)===m).reduce((a,x)=>a+Number(x.amount||0),0);const d=db.daily.filter(x=>monthOf(x.date)===m);return {expenses:exp+ d.reduce((a,x)=>a+Number(x.expenses||0),0),purchases:pur+d.reduce((a,x)=>a+Number(x.purchases||0),0)}}
function yearData(y){const ms=String(y);let invoices=0,expenses=0,purchases=0,salaries=0;db.daily.filter(x=>String(x.date).startsWith(ms+'-')).forEach(x=>{invoices+=Number(x.invoices||0);expenses+=Number(x.expenses||0);purchases+=Number(x.purchases||0)});expenses+=db.expenses.filter(x=>String(x.date).startsWith(ms+'-')).reduce((a,x)=>a+Number(x.amount||0),0);purchases+=db.purchases.filter(x=>String(x.date).startsWith(ms+'-')).reduce((a,x)=>a+Number(x.amount||0),0);salaries=db.payments.filter(x=>String(x.date).startsWith(ms+'-')).reduce((a,x)=>a+Number(x.amount||0),0);const profit=invoices-expenses-purchases-salaries;const without=-expenses-purchases-salaries;const cost=expenses+purchases+salaries;return {invoices,expenses,purchases,salaries,profit,without,margin:invoices?profit/invoices*100:0,marginWithout:cost?without/cost*100:0}}
function renderAnnual(){const y=Number($('yearPick').value)||new Date().getFullYear(),x=yearData(y);$('annualBox').innerHTML=`<div class="hero"><div class="hero-title">Total ${y} — صافي الربح مع الفواتير</div><div class="hero-value ${x.profit>=0?'ok':'danger-text'}">${money(x.profit)}</div><div class="hero-note">هامش الربح: ${x.margin.toFixed(2)}%</div></div><div class="grid"><div class="card stat"><div class="label">إجمالي المبيعات / الفواتير</div><div class="big">${money(x.invoices)}</div></div><div class="card stat"><div class="label">المصاريف</div><div class="big">${money(x.expenses)}</div></div><div class="card stat"><div class="label">المشتريات</div><div class="big">${money(x.purchases)}</div></div><div class="card stat"><div class="label">الأجور</div><div class="big">${money(x.salaries)}</div></div><div class="card stat"><div class="label">صافي الربح مع الفواتير</div><div class="big ${x.profit>=0?'ok':'warn'}">${money(x.profit)}</div></div><div class="card stat"><div class="label">صافي بدون الفواتير</div><div class="big warn">${money(x.without)}</div><div class="muted" style="font-size:9px;margin-top:4px">هامش بدون الفواتير: ${x.marginWithout.toFixed(2)}%</div></div></div>`}
function autoArchiveCompletedMonths(){const now=new Date();const current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const months=[...new Set(db.daily.map(x=>monthOf(x.date)).filter(Boolean))];let changed=false;for(const m of months){if(m===current)continue;const [yy,mm]=m.split('-').map(Number);const daysInMonth=new Date(yy,mm,0).getDate();const dates=new Set(db.daily.filter(x=>monthOf(x.date)===m).map(x=>x.date));let complete=true;for(let day=1;day<=daysInMonth;day++){const ds=`${yy}-${String(mm).padStart(2,'0')}-${String(day).padStart(2,'0')}`;if(!dates.has(ds)){complete=false;break}}if(complete&&!db.archive.some(a=>a.month===m)){const md=monthData(m);db.archive.push(md);changed=true}}if(changed)localStorage.setItem(KEY,JSON.stringify(db))}
function monthData(m){const days=db.daily.filter(x=>monthOf(x.date)===m);const invoices=days.reduce((a,x)=>a+Number(x.invoices||0),0),baseExp=days.reduce((a,x)=>a+Number(x.expenses||0),0),basePur=days.reduce((a,x)=>a+Number(x.purchases||0),0),extraExp=db.expenses.filter(x=>monthOf(x.date)===m).reduce((a,x)=>a+Number(x.amount||0),0),extraPur=db.purchases.filter(x=>monthOf(x.date)===m).reduce((a,x)=>a+Number(x.amount||0),0),expenses=baseExp+extraExp,purchases=basePur+extraPur,salaries=db.payments.filter(x=>monthOf(x.date)===m).reduce((a,x)=>a+Number(x.amount||0),0);return {month:m,invoices,expenses,purchases,salaries,profitWithInvoices:invoices-expenses-purchases-salaries,profitWithoutInvoices:-expenses-purchases-salaries,days:days.length}}
function renderMonth(){const m=$("monthPick").value||localDate().slice(0,7),x=monthData(m);$("monthBox").innerHTML=`<div class="hero"><div class="hero-title">صافي ربح ${esc(m)}</div><div class="hero-value ${x.profitWithInvoices>=0?'ok':'danger-text'}">${money(x.profitWithInvoices)}</div><div class="hero-note">الفواتير − المصاريف − المشتريات − الأجور</div></div><div class="grid"><div class="card stat"><div class="icon">📅</div><div class="label">أيام مسجلة</div><div class="big">${x.days}</div></div><div class="card stat"><div class="icon">💵</div><div class="label">الفواتير</div><div class="big">${money(x.invoices)}</div></div><div class="card stat"><div class="icon">💸</div><div class="label">المصاريف</div><div class="big">${money(x.expenses)}</div></div><div class="card stat"><div class="icon">🛒</div><div class="label">المشتريات</div><div class="big">${money(x.purchases)}</div></div><div class="card stat"><div class="icon">👥</div><div class="label">الأجور</div><div class="big">${money(x.salaries)}</div></div><div class="card stat"><div class="icon">📈</div><div class="label">الربح بدون الفواتير</div><div class="big warn">${money(x.profitWithoutInvoices)}</div></div></div>`;renderMonthChart()}
function renderMonthChart(){const arr=[];const base=new Date();base.setDate(1);for(let i=5;i>=0;i--){const d=new Date(base.getFullYear(),base.getMonth()-i,1);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;arr.push(monthData(m))}const max=Math.max(1,...arr.map(x=>Math.abs(x.profitWithInvoices)));$("monthChart").innerHTML=arr.map(x=>{const h=Math.max(3,Math.round(Math.abs(x.profitWithInvoices)/max*92));return `<div class="bar-col"><div class="bar-val">${x.profitWithInvoices.toFixed(0)}</div><div class="bar" style="height:${h}px;opacity:${x.profitWithInvoices<0?.55:1}"></div><div class="bar-label">${x.month.slice(5)}</div></div>`}).join('')}
function archiveCurrentMonth(){const m=$("monthPick").value||localDate().slice(0,7),x=monthData(m),old=db.archive.find(a=>a.month===m);if(old)Object.assign(old,x);else db.archive.push(x);save();renderAll();toast('تمت أرشفة الشهر ✓')}
function renderArchive(){const rows=[...db.archive].sort((a,b)=>b.month.localeCompare(a.month)).map(x=>`<tr><td>${esc(x.month)}</td><td>${money(x.invoices)}</td><td>${money(x.expenses)}</td><td>${money(x.purchases)}</td><td>${money(x.salaries)}</td><td class="${x.profitWithInvoices>=0?'ok':'warn'}">${money(x.profitWithInvoices)}</td><td><button class="btn danger" onclick="deleteArchive('${esc(x.month)}')">حذف</button></td></tr>`).join('');$("archiveTable").innerHTML=rows?`<table><tr><th>الشهر</th><th>الفواتير</th><th>المصاريف</th><th>المشتريات</th><th>الأجور</th><th>الربح</th><th></th></tr>${rows}</table>`:`<div class="empty">لا يوجد أرشيف بعد</div>`}
function deleteArchive(m){if(confirm('حذف أرشيف هذا الشهر؟')){db.archive=db.archive.filter(x=>x.month!==m);save();renderAll();toast('تم الحذف')}}

function exportBackup(){const data={...db,exportedAt:new Date().toISOString(),app:'كافيه طلة الشمالي'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`talat-shamali-backup-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('تم إنشاء النسخة الاحتياطية ✓')}
$("importFile").addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!Array.isArray(x.daily)||!Array.isArray(x.employees)||!Array.isArray(x.payments)){throw new Error('invalid')}if(confirm('سيتم استبدال البيانات الحالية بالنسخة المختارة. هل أنت متأكد؟')){db=normalizeDb(x);save();renderAll();toast('تم استيراد النسخة ✓')}}catch(err){alert('ملف النسخة الاحتياطية غير صالح')}};reader.readAsText(file);e.target.value=''})
function resetAll(){if(confirm('سيتم حذف كل بيانات الموقع نهائيًا من هذا الجهاز. هل أخذت نسخة احتياطية؟')){localStorage.removeItem(KEY);location.reload()}}

const LOGIN_USER='Mohammed',LOGIN_PASS='jasser';
function applyLogin(){$("loginScreen").style.display=localStorage.getItem('talatLogged')==='1'?'none':'flex'}
$("loginForm").onsubmit=e=>{e.preventDefault();if($("loginUser").value===LOGIN_USER&&$("loginPass").value===LOGIN_PASS){localStorage.setItem('talatLogged','1');$("loginError").style.display='none';applyLogin()}else $("loginError").style.display='block'};
function logout(){localStorage.removeItem('talatLogged');applyLogin()}
function renderAll(){autoArchiveCompletedMonths();renderHome();renderDaily();renderSalaries();renderAbuFadi();renderEntries('expenses');renderEntries('purchases');renderMonth();renderAnnual();renderArchive();updateDailyPreview()}
$("dashDate").addEventListener('change',renderHome);$("monthPick").addEventListener('change',renderMonth);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$("installAppBtn").style.display='block'});
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$("installAppBtn").style.display='none'}else toast('من قائمة المتصفح اختر إضافة إلى الشاشة الرئيسية')}
window.addEventListener('appinstalled',()=>$("installAppBtn").style.display='none');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}))}
applyLogin();loadSyncSettings(true);renderAll();loadDailyInputs(localDate());
